services:
  postgres:
    image: postgres:15
    container_name: ansesstral-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ansesstral_password
      POSTGRES_DB: ansesstral_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
